messages:
  only-players: "&cЭта команда только для игроков!"
  no-permission: "&cУ вас нет прав!"
  home-set: "&aДом успешно установлен!"
  no-home: "&cУ вас нет сохраненного дома!"
  teleported: "&aВы телепортированы домой!"
  home-deleted: "&cВаш дом удален!"
  world-not-found: "&cМир не найден!"
  error: "&cПроизошла ошибка при телепортации!"